version: '3.3'
services:
  blogon:
    build:
      context: ./
      dockerfile: Dockerfile
    image: blogon
    ports:
      - "8443:8443"
      - "8080:8080"
    networks:
      - network1

networks:
  network1:

